"""Shared pytest fixtures for the agentbox UI test suite.

Every fixture points the app's file stores at temporary copies of the real
``agents/``, ``prompts/``, and a rendered LiteLLM config so tests never touch the
repository. Imports of app modules (``config``, ``main``, ``dagster``) are done
lazily inside fixtures: those modules are built across later phases, so the suite
stays collectable before they exist.
"""
import shutil
from pathlib import Path

import pytest

# Repository root: ui/tests/conftest.py -> ui/ -> repo root.
REPO_ROOT = Path(__file__).resolve().parents[2]


@pytest.fixture
def tmp_agents(tmp_path):
    """A writable copy of every repo agents/*.yaml in a temp directory."""
    dest = tmp_path / "agents"
    dest.mkdir()
    src = REPO_ROOT / "agents"
    if src.is_dir():
        for f in src.glob("*.yaml"):
            shutil.copy(f, dest / f.name)
    return dest


@pytest.fixture
def tmp_prompts(tmp_path):
    """A writable copy of every repo prompts/*.md in a temp directory."""
    dest = tmp_path / "prompts"
    dest.mkdir()
    src = REPO_ROOT / "prompts"
    if src.is_dir():
        for f in src.glob("*.md"):
            shutil.copy(f, dest / f.name)
    return dest


@pytest.fixture
def tmp_templates(tmp_path):
    """A writable copy of the product examples starters (examples/config/agents/*.yaml).

    The create form's template picker reads starters from here (config.TEMPLATES_DIR), not
    from the instance agents dir (R7).
    """
    dest = tmp_path / "templates"
    dest.mkdir()
    src = REPO_ROOT / "examples" / "config" / "agents"
    if src.is_dir():
        for f in src.glob("*.yaml"):
            shutil.copy(f, dest / f.name)
    return dest


@pytest.fixture
def litellm_cfg(tmp_path):
    """A rendered LiteLLM config in a temp dir, standing in for litellm.rendered.yaml.

    The rendered config is instance data (generated by litellm/generate.py from the product
    template + overlay, US6). Seed the fixture from the example overlay's model_list so the
    UI's alias-completion (config.LITELLM_RENDERED) has the real tier names to read.
    """
    dest = tmp_path / "litellm.rendered.yaml"
    src = REPO_ROOT / "examples" / "config" / "litellm.overlay.yaml"
    if src.is_file():
        shutil.copy(src, dest)
    return dest


@pytest.fixture
def settings(monkeypatch, tmp_agents, tmp_prompts, tmp_templates, litellm_cfg):
    """Point ui/config.py at the temp stores for the duration of a test."""
    import config

    monkeypatch.setattr(config, "AGENTS_DIR", str(tmp_agents))
    monkeypatch.setattr(config, "PROMPTS_DIR", str(tmp_prompts))
    monkeypatch.setattr(config, "TEMPLATES_DIR", str(tmp_templates))
    monkeypatch.setattr(config, "LITELLM_RENDERED", str(litellm_cfg))
    return config


@pytest.fixture
def client(settings):
    """A FastAPI TestClient bound to the app, with stores pointed at temp dirs."""
    from fastapi.testclient import TestClient

    from main import app

    return TestClient(app)


@pytest.fixture
def dagster_stub(monkeypatch):
    """Replace the Dagster reload/status calls with canned outcomes.

    Returns a small object whose ``reload_result`` / ``status_result`` attributes
    a test can set before acting; defaults describe a healthy, reachable Dagster.
    """
    import dagster

    class Stub:
        reload_result = {"ok": True, "message": "Workspace reloaded"}
        status_result = {"url": "http://dagster-test:3000", "reachable": True}

    stub = Stub()

    async def fake_reload():
        return stub.reload_result

    async def fake_status():
        return stub.status_result

    monkeypatch.setattr(dagster, "reload", fake_reload)
    monkeypatch.setattr(dagster, "status", fake_status)
    return stub
