#!/usr/bin/env python3
"""One-off migration (spec 005): move agent triggering out of agents/*.yaml.

For EVERY ``agents/*.yaml``: strip the top-level ``schedule:`` line and bump the
``# agentbox-schema:`` stamp to 3. For every NON-template file (basename not starting with
``_``) whose ``schedule`` was non-empty: write ``<name>:\n  cron: "<value>"`` into
``automation/migrated.yaml``. Manual-only (``schedule: ""``) and templates contribute no
entry (templates share the placeholder name ``my-agent`` — FR-012).

Run once from the repo root: ``python3 scripts/migrate-schedules.py``. Idempotent — a second
run finds no ``schedule:`` lines, stamps already at 3, and every entry already present, so it
changes nothing (SC-002).
"""
import glob
import os
import re
import sys

import yaml

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AGENTS_DIR = os.path.join(REPO_ROOT, "agents")
AUTOMATION_DIR = os.path.join(REPO_ROOT, "automation")
MIGRATED = os.path.join(AUTOMATION_DIR, "migrated.yaml")

_SCHEDULE_LINE = re.compile(r"^schedule\s*:.*$", re.MULTILINE)
_STAMP = re.compile(r"^(# agentbox-schema:\s*)\d+", re.MULTILINE)

_HEADER = (
    "# Generated by scripts/migrate-schedules.py (spec 005) — agent triggers moved out of\n"
    "# agents/*.yaml. Map keyed by agent name; each value is one trigger: `cron: \"...\"` or\n"
    "# `on_demand: true`. The management UI's Automation view also writes this file.\n"
)


def _strip_schedule_and_bump(text: str) -> str:
    """Remove the top-level ``schedule:`` line(s) and normalize the schema stamp to 3.

    A file that already carries ``# agentbox-schema: N`` has it bumped to 3; a file with no
    stamp (hand-written) gets one prepended, so every agent file ends at schema 3.
    """
    without = _SCHEDULE_LINE.sub("", text)
    # Collapse a blank line left where the schedule line was, but keep the file readable.
    without = re.sub(r"\n\n\n+", "\n\n", without)
    if _STAMP.search(without):
        return _STAMP.sub(r"\g<1>3", without)
    return "# agentbox-schema: 3\n" + without


def _load_entries() -> dict:
    """Existing automation/migrated.yaml as a dict (empty if absent), so a re-run merges."""
    if not os.path.exists(MIGRATED):
        return {}
    with open(MIGRATED, encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def _dump_entries(entries: dict) -> str:
    body = yaml.safe_dump(entries, sort_keys=True, default_flow_style=False, width=10**9)
    return _HEADER + body


def main() -> int:
    changed = []
    new_entries: dict[str, dict] = {}

    for path in sorted(glob.glob(os.path.join(AGENTS_DIR, "*.yaml"))):
        with open(path, encoding="utf-8") as f:
            text = f.read()
        try:
            cfg = yaml.safe_load(text) or {}
        except yaml.YAMLError as e:
            print(f"! skipping {os.path.basename(path)}: not valid YAML ({e})", file=sys.stderr)
            continue

        new_text = _strip_schedule_and_bump(text)
        if new_text != text:
            with open(path, "w", encoding="utf-8") as f:
                f.write(new_text)
            changed.append(os.path.basename(path))

        # Entry only for non-template files with a non-empty schedule.
        is_template = os.path.basename(path).startswith("_")
        schedule = cfg.get("schedule")
        name = cfg.get("name")
        if not is_template and name and isinstance(schedule, str) and schedule.strip():
            new_entries[name] = {"cron": schedule.strip()}

    # Merge new cron entries into any existing automation/migrated.yaml (preserving entries a
    # user or a prior run already wrote), and write only if the result differs (idempotency).
    entries = _load_entries()
    merged = dict(entries)
    merged.update(new_entries)
    if merged and merged != entries:
        os.makedirs(AUTOMATION_DIR, exist_ok=True)
        with open(MIGRATED, "w", encoding="utf-8") as f:
            f.write(_dump_entries(merged))
        print(f"→ wrote {len(new_entries)} cron entr{'y' if len(new_entries)==1 else 'ies'} to automation/migrated.yaml")
    elif not merged:
        print("→ no schedules to migrate")
    else:
        print("→ automation/migrated.yaml already up to date")

    if changed:
        print(f"→ stripped `schedule` / bumped stamp in {len(changed)} agent file(s): {', '.join(changed)}")
    else:
        print("→ no agent files needed changes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
