"""Read, validate, and write agent triggers under automation/ (spec 005).

The agent schema no longer carries a `schedule`; *when* an agent runs lives here — a
directory of YAML maps keyed by agent name, each value a `cron` or `on_demand` trigger. The
Automation view reads every file (`per_agent_view`) and writes the canonical
`automation/migrated.yaml` (`write`), then reloads Dagster. Validation mirrors the
orchestrator's (contract automation-format §3); the shared five-field cron rule is duplicated
here deliberately (research R6) and pinned to the orchestrator copy by a test.
"""
from __future__ import annotations

import glob
import os

import yaml

import config
import agents_store


class AutomationError(Exception):
    """A rejected automation edit; ``field`` names the offending agent for the UI (FR-009/010)."""

    def __init__(self, message: str, field: str | None = None):
        self.message = message
        self.field = field
        super().__init__(message)


def is_valid_cron(value) -> bool:
    """Five fields, no @-macros — the rule the removed `schedule` field used (FR-009).

    Twin of ``orchestrator/factory.py:is_valid_cron`` (separate containers, no shared import);
    this UI copy additionally runs ``croniter.is_valid`` as the stricter authoring guard.
    """
    if not isinstance(value, str):
        return False
    s = value.strip()
    if not s or s.startswith("@"):
        return False
    if len(s.split()) != 5:
        return False
    from croniter import croniter
    return croniter.is_valid(s)


_HEADER = (
    "# Generated by the agentbox UI Automation view (spec 005) — agent triggers.\n"
    "# Map keyed by agent name; each value is one trigger: `cron: \"...\"` or `on_demand: true`.\n"
)


def _automation_dir() -> str:
    return config.AUTOMATION_DIR


def _migrated_path() -> str:
    return os.path.join(_automation_dir(), "migrated.yaml")


def _normalize_trigger(name: str, value, file: str) -> dict | None:
    """One entry value → ``{"cron": str}`` (stored) or ``None`` (on-demand). Raises on invalid."""
    if value is None:
        return None
    if not isinstance(value, dict):
        raise AutomationError(f'{file}: entry "{name}" must be a map with one trigger', field=name)
    has_cron = "cron" in value and value.get("cron") not in (None, "")
    has_on_demand = bool(value.get("on_demand"))
    if has_cron and has_on_demand:
        raise AutomationError(f'entry "{name}" declares both cron and on_demand — pick one', field=name)
    if has_cron:
        cron = value["cron"]
        if not is_valid_cron(cron):
            raise AutomationError(
                f'entry "{name}" has invalid cron "{cron}" — five fields, no @-macros', field=name,
            )
        return {"cron": str(cron).strip()}
    return None


def load() -> tuple[dict, dict]:
    """Merge automation/*.yaml → ``(triggers, sources)``.

    ``triggers`` maps a name to ``{"cron": str}`` (on-demand agents omitted); ``sources`` maps
    a name to the file it came from. Raises AutomationError on a duplicate key across files or
    an invalid trigger (contract automation-format §3).
    """
    triggers: dict[str, dict] = {}
    sources: dict[str, str] = {}
    for path in sorted(glob.glob(os.path.join(_automation_dir(), "*.yaml"))):
        file = "automation/" + os.path.basename(path)
        with open(path, encoding="utf-8") as f:
            data = yaml.safe_load(f)
        if not data:
            continue
        if not isinstance(data, dict):
            raise AutomationError(f"{file}: top level must be a map keyed by agent name")
        for name, value in data.items():
            if name in sources:
                raise AutomationError(
                    f'"{name}" is declared by both {sources[name]} and {file}', field=name,
                )
            trig = _normalize_trigger(name, value, file)
            if trig is not None:
                triggers[name] = trig
            sources[name] = file
    return triggers, sources


def known_agent_names() -> set[str]:
    """Every agent name from agents/*.yaml — templates and disabled included (contract §3)."""
    names: set[str] = set()
    for path in glob.glob(os.path.join(config.AGENTS_DIR, "*.yaml")):
        try:
            with open(path, encoding="utf-8") as f:
                cfg = yaml.safe_load(f)
        except (OSError, yaml.YAMLError):
            continue
        if isinstance(cfg, dict) and cfg.get("name"):
            names.add(cfg["name"])
    return names


def per_agent_view() -> list[dict]:
    """One row per NON-template agent (disabled included) with its current trigger.

    ``mode`` is ``"asset"`` when the agent declares `produces` (feature 004), else ``"job"``.
    A missing agent defaults to on-demand.
    """
    triggers, _ = load()
    rows: list[dict] = []
    for path in sorted(glob.glob(os.path.join(config.AGENTS_DIR, "*.yaml"))):
        stem = os.path.basename(path)[:-5]
        if stem.startswith("_"):
            continue  # templates are not real agents (contract ui-automation §3)
        info = agents_store.read_agent(stem)
        agent = info.get("agent") or {}
        name = info.get("name") or stem
        rows.append({
            "name": name,
            "harness": agent.get("harness"),
            "mode": "asset" if agent.get("asset") else "job",
            # `enabled` controls whether Dagster registers the agent at all — a disabled agent's
            # trigger is inert until it is enabled (surfaced as a badge in the view). Default True.
            "enabled": agent.get("enabled", True) is not False,
            "trigger": triggers.get(name, {"on_demand": True}),
        })
    return rows


def validate(triggers: dict, known: set[str] | None = None) -> None:
    """Validate an incoming trigger set before writing (FR-009/FR-010). Raises AutomationError."""
    known = known_agent_names() if known is None else known
    for name, value in triggers.items():
        if name not in known:
            raise AutomationError(f'"{name}" names no agent — no agents/*.yaml declares it', field=name)
        _normalize_trigger(name, value, "automation/migrated.yaml")  # raises on both/invalid cron


def write(triggers: dict) -> str:
    """Rewrite the canonical automation/migrated.yaml from ``triggers`` (cron entries only).

    ``on_demand``/absent agents are simply omitted. Returns the path written.
    """
    entries = {}
    for name, value in triggers.items():
        trig = _normalize_trigger(name, value, "automation/migrated.yaml")
        if trig is not None:
            entries[name] = trig
    os.makedirs(_automation_dir(), exist_ok=True)
    body = yaml.safe_dump(entries, sort_keys=True, default_flow_style=False, width=10**9) if entries else ""
    with open(_migrated_path(), "w", encoding="utf-8") as f:
        f.write(_HEADER + body)
    return _migrated_path()
